### ISSUE TITLE
Rename the font

### ISSUE THREAD

**Issue by andreaslarsen** [andreaslarsen/ifelse#10]
Mono16 probably isn't the most colloquial/memorable name....any suggestions?

**Comment by chase** [comment]
Personally, I think it is fine as it is.
Here are my thoughts:
* It distinguishes itself from others. At least more than say, DeJavu Sans.
* It is short to type and doesn't have many conflicting Google search results.
* Mono infers that it is monospaced, yet does not belong to larger family of fonts.
* The 16, though the ideal font size, works together with Mono to represent a common occurrence in code where symbols and variables cannot begin with a number, but may follow with a number.

**Comment by andreaslarsen** [comment]
Yeah...you are probably right. It's just the number in the name...not many other fonts use that although it is a common occurrence in coding.  

Could be fun with something like

ifElse 

or something similar that is still code related but without mono, code, pro etc. in the name

**Comment by andreaslarsen** [comment]
or println

**Comment by andreaslarsen** [comment]
Oh well, talked with some other guys and they liked ifElse too so went ahead and changed it - updated website here: http://andreaslarsen.github.io/ifElse
I know the name is a bit generic but when I told someone I had made a font named ifElse he immediately guessed it was a coding font which is a plus.

**Comment by andreaslarsen** [comment]
Should have been lowercase...http://andreaslarsen.github.io/ifelse
