### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by andreaslarsen** [andreaslarsen/ifelse#7]
First try available now in 0.24. This is what I have so far. 

![screen shot 2015-04-06 at 17 29 59](https://cloud.githubusercontent.com/assets/3859425/7006674/4a7ed872-dc83-11e4-8563-5b31f03cf97d.png)

What I need is

- [x] **Feedback on the design**

- [x] **Any examples of fonts where 3, З and Э are clearly distinguishable?** *

- [x] **Any missing characters?**

- [x] **Russian code samples** for the website in one of these languages: markup+css+clike+javascript+python+ruby+swift

*The best I've found is PT Sans but this requires a different 3 - does coding programs generally "know" you're writing e.g. Russian so I could use language based substitution?

PT Sans
![screen shot 2015-04-06 at 15 58 50](https://cloud.githubusercontent.com/assets/3859425/7005172/f0f6107a-dc75-11e4-9dbc-96c837b86255.png)

**Comment by K900** [comment]
This is З (the letter), Э and 3 (the number) in Consolas: ![](http://i.imgur.com/De4UVcB.png)
DejaVu Sans Mono: ![](http://i.imgur.com/nZOz9Ey.png)
Liberation Mono: ![](http://i.imgur.com/H1H3W5g.png)
Courier New: ![](http://i.imgur.com/pftr12T.png)
Fira Mono: ![](http://i.imgur.com/SSe9bJ7.png)

**Comment by K900** [comment]
Some general observations: Э is always a single curve, so the main problem is capital З versus 3. Most fonts seem to make the letter wider than the number. 

DejaVu is absolutely terrible: ![](http://i.imgur.com/TRowU7m.png)

Liberation is better: ![](http://i.imgur.com/Zb58Bqi.png)

Consolas is OK: ![](http://i.imgur.com/gsitOHJ.png)

Fira is second best: ![](http://i.imgur.com/oNfQTiH.png)

Courier New wins by being serif: ![](http://i.imgur.com/vIC2wx9.png)

**Comment by andreaslarsen** [comment]
@K900 thank you, great that we both agree on PT (mono/sans) being the best option. 
I will not change the default letter 3 in the font so it has to be a stylistic alternate (as e.g. slashed zero is now) or, even better, language based substitution. 

I will try to make the latter and upload for you to test in your terminal/coding program and if it doesn't work the use the stylistic alternate.

I went a little nuts and added some more letters - this should cover the most, right?

![screen shot 2015-04-06 at 17 29 59](https://cloud.githubusercontent.com/assets/3859425/7006674/4a7ed872-dc83-11e4-8563-5b31f03cf97d.png)

**Comment by andreaslarsen** [comment]
![screen shot 2015-04-06 at 17 53 00](https://cloud.githubusercontent.com/assets/3859425/7006970/d11e3d08-dc85-11e4-9159-f568681c99f7.png)

I just pushed 0.24 with cyrillic support for Mono16 Normal - could you test?

**Comment by K900** [comment]
Wow, it's pretty crazy that fonts even get to do that. I wonder how to preserve consistency between code (i.e. English) and Russian text though...

**Comment by K900** [comment]
...aaaand Sublime entirely ignores the hints. ![](http://i.imgur.com/CKkywAs.png)

**Comment by andreaslarsen** [comment]
locl usually works by following the application and/or document settings but obviously the program has to support it which sublime apparently doesn't :/ 

Locl doesn't change the letter so it doesn't affect code - it just changes how the letter is shown if the font and the program supports it. 

I won't remove the locl as it's nice to have for e.g. web use but I'll add is as stylistic alternate too. 

Any other thoughts on the design?

**Comment by andreaslarsen** [comment]
Latest upload includes 3 as style set 2 - just follow this guide:
https://github.com/andreaslarsen/mono16/blob/master/Resources/Readme.pdf

**Comment by andreaslarsen** [comment]
![screen shot 2015-04-06 at 20 33 57](https://cloud.githubusercontent.com/assets/3859425/7009684/4a344654-dc9c-11e4-8088-522f929bd33a.png)

5 3 E ZE

**Comment by andreaslarsen** [comment]
Added a cyrillic pdf

**Comment by K900** [comment]
Looking at it now: lower case ф doesn't have to be that tall, Д is fine, Щ usually has the lower right tick thing moved a bit to the right of the Ш part, you should be able to see it here on GitHub.

**Comment by K900** [comment]
Also, б's top part might be a bit too straight of a line, it kind of looks like 6 now.

**Comment by andreaslarsen** [comment]
Щ: It's a space issue...not sure how I can draw it otherwise: 
![screen shot 2015-04-07 at 12 17 31](https://cloud.githubusercontent.com/assets/3859425/7021274/3f3fe580-dd20-11e4-961d-a321134c22f9.png)

I have updated б and ф too, better or?
https://github.com/andreaslarsen/mono16/blob/master/Resources/Testing/Mono16cyrillic.pdf

**Comment by K900** [comment]
б is nice now, not sure about ф - it looks like most fonts let the vertical line drop a bit below the baseline. Here's PT Mono: ![](http://i.imgur.com/LzRAVl6.png). About Щ: maybe make the Ш part narrower?

**Comment by andreaslarsen** [comment]
So more like this?
![screen shot 2015-04-07 at 13 24 51](https://cloud.githubusercontent.com/assets/3859425/7022186/9cfcfe16-dd29-11e4-9e94-805915150883.png)
![screen shot 2015-04-07 at 13 25 20](https://cloud.githubusercontent.com/assets/3859425/7022191/a09a4380-dd29-11e4-8117-2bf2eb2fa251.png)

**Comment by andreaslarsen** [comment]
Щ: problem is I have to stick to the grid and that would make it very narrow.

Current:
![screen shot 2015-04-07 at 13 24 23](https://cloud.githubusercontent.com/assets/3859425/7022213/c68d1626-dd29-11e4-804a-c4628e48860b.png)

**Comment by K900** [comment]
Yeah, something like that probably. It doesn't really have to be the same height as the "d", but that's up to you. And yeah, not really sure what to do about Щ. You can't go any wider than that, right?

**Comment by andreaslarsen** [comment]
I can maybe go wider but that depends on which letters usually come after Щ ?

**Comment by K900** [comment]
According to [this](http://practicalcryptography.com/cryptanalysis/letter-frequencies-various-languages/russian-letter-frequencies/), bigrams that start with Щ, sorted by frequency:

> ЩЕ 397624
> ЩИ 280738
> ЩА 121761
> ЩЁ 40078
> ЩН 21884
> ЩУ 18341
> ЩЬ 17426
> ЩР 1289
> ЩО 687
> ЩВ 462
> ЩП 326
> ЩС 265
> ЩК 157
> ЩМ 152
> ЩД 110
> ЩЯ 103
> ЩБ 102
> ЩТ 99
> ЩГ 71
> ЩЛ 62
> ЩЗ 57
> ЩФ 35
> ЩЧ 34
> ЩЩ 32
> ЩЮ 30
> ЩЭ 28
> ЩШ 26
> ЩХ 26
> ЩЙ 25
> ЩЦ 15
> ЩЖ 14
> ЩЫ 11
> ЩЪ 1

Not sure what their methodology was, but this looks more or less correct at a quick glance.

**Comment by andreaslarsen** [comment]
great find! 
We could get away with it if we assume people don't write that much ALL CAPS in Russian in code...
Only мд are really problematic and they aren't that common.

![screen shot 2015-04-07 at 13 55 10](https://cloud.githubusercontent.com/assets/3859425/7022593/d8e611e8-dd2d-11e4-93eb-418449f1d497.png)

**Comment by andreaslarsen** [comment]
![screen shot 2015-04-07 at 13 58 22](https://cloud.githubusercontent.com/assets/3859425/7022633/316f725a-dd2e-11e4-834d-d468e84d2c4e.png)

**Comment by K900** [comment]
I'm pretty sure ЩМ/ЩД is only ever used in abbreviations. Also, ЩД is actually broken even in Arial or whatever it is GitHub uses. The new Щ is definitely a lot better. Now that I notice it though: why are E and Ё different in height? That looks kind of weird.

**Comment by andreaslarsen** [comment]
We'll keep it like this then. 
The Ё looks weird but it and all other capitals with diacritics are "squeezed" to preserve the whitespace between the lines which is important when using small line heights like this:

![screen shot 2015-04-07 at 13 10 40](https://cloud.githubusercontent.com/assets/3859425/7022004/90de24c2-dd27-11e4-8089-94055731aa3e.png)

**Comment by andreaslarsen** [comment]
I've now pushed 2.5 for normal with all the adjustments we've talked about here + I made Capital DE a little wider to the left.

**Comment by andreaslarsen** [comment]
It would be great if you could find some code samples where cyrillics are also used :) (for the website)

**Comment by chase** [comment]
At least in my experience, most code is written in English and occasionally the comments are written in a shared or native language of the developers.
You could always use the pangram that Gnome uses:

**Comment by andreaslarsen** [comment]
Ending up finding some russian code myself (and czech and french) so think we're covered now - but I'll probably add a pangrams page too - good idea!
